"""Add roles and permissions (RBAC)

Revision ID: f7779d0d97e6
Revises: fe0fba7d383a
Create Date: 2026-08-02 17:43:16.455197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7779d0d97e6'
down_revision: Union[str, Sequence[str], None] = 'fe0fba7d383a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###

    # Seed data — deliberately NOT importing the live ORM models here.
    # Migrations must stay replayable exactly as written even after the
    # application's models change or get deleted; sa.table()/sa.column()
    # are lightweight, migration-local stand-ins just for this insert.
    roles = sa.table('roles', sa.column('id', sa.Integer), sa.column('name', sa.String))
    permissions = sa.table('permissions', sa.column('id', sa.Integer), sa.column('name', sa.String))
    role_permissions = sa.table('role_permissions', sa.column('role_id', sa.Integer), sa.column('permission_id', sa.Integer))

    op.bulk_insert(roles, [{'id': 1, 'name': 'member'}, {'id': 2, 'name': 'admin'}])
    op.bulk_insert(permissions, [{'id': 1, 'name': 'view_admin_dashboard'}])
    op.bulk_insert(role_permissions, [{'role_id': 2, 'permission_id': 1}])  # admin -> view_admin_dashboard

    # No user gets assigned a role here on purpose — this migration runs
    # before it's known which users (if any) exist yet, and handing out
    # the admin role automatically would be a real privilege-escalation
    # bug, not a convenience. Assigning member/admin to specific users is
    # a separate, deliberate action (see the register() wiring for member,
    # and a manual DB action for the first admin).


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
